{
    "run_timestamp": "2025-01-31T11:26:08.255312",
    "user": "unknown",
    "inputs": {
        "assumption_table": "s3://valuation-model/term/run2/Assumptions/Assumptions.xlsx",
        "model_point_files": "s3://valuation-model/term/run2/model point files/",
        "valuation_date": "2024-06-30",
        "projection_period": 30,
        "product_groups": [
            "C_TERM"
        ]
    },
    "execution_details": {
        "start_time": "2025-01-31T11:26:08.255312",
        "end_time": "2025-01-31T11:26:12.247868",
        "duration_seconds": 3.992556,
        "status": "error"
    },
    "output_location": null,
    "error_message": "[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\\\Users\\\\zhang\\\\AppData\\\\Local\\\\Temp\\\\tmpfxwgil7q.xlsx'"
}